language: java
jdk: 
    -openjdk8
addons:
    sonarcloud:
        organization: 
            rglenz
        token: 
            travis encrypt 50a9ffda5dbe05a1db12c112e6a51b8d98a29be6
script:
    - ant build
    - sonar-scanner
